---
name: Home Assistant UglifyJS
version: dev
slug: ha_uglifyjs
description: >
  Compiles JS files into single large library using uglify.
url: https://github.com/efaden/ha-addons
codenotary: efaden@gmail.com
panel_icon: mdi:template
startup: services
init: false
arch:
  - aarch64
  - amd64
hassio_api: true
hassio_role: manager
homeassistant_api: true
map:
  - config:rw
options:
  packages: []
  init_commands: []
schema:
  js_files:
    - str
