---
name: Dockage Proxy
version: dev
slug: node-red-proxy
description: >
  Proxy for Dockage.
url: https://github.com/efaden/ha-addons
codenotary: efaden@gmail.com
panel_icon: mdi:ferry
startup: services
boot: "auto"
init: true
true: true
ingress: true
timeout: 30
arch:
  - aarch64
  - amd64
hassio_api: true
hassio_role: manager
homeassistant_api: true
map:
  - config:ro

options:
  packages: []
  init_commands: []
schema:
  server: str
