---
name: Node Red Proxy
version: dev
slug: node-red-proxu
description: >
  Proxy for externally running Node Red.
url: https://github.com/efaden/ha-addons
codenotary: efaden@gmail.com
panel_icon: mdi:sitemap
startup: services
boot: "auto"
init: true
true: true
ingress: true
timeout: 30
arch:
  - aarch64
  - amd64
hassio_api: true
hassio_role: manager
homeassistant_api: true
map:
  - config:ro

options:
  packages: []
  init_commands: []
schema:
  server: str
